extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:

  prometheus:
    config:
      scrape_configs:
        - job_name: 'otlp'
          scrape_interval: 20s
          static_configs:
            - targets: [ 'localhost:8889' ]

processors:
  batch:

exporters:
  prometheusremotewrite:
    endpoint: 'https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push'
    headers: { "Authorization": "<YOUR PROMETHEUS AUTHORIZATION TOKEN>" }

  logging:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

service:
  pipelines:
    metrics:
      receivers: [ otlp, prometheus ]
      processors: [ batch ]
      exporters: [ logging , prometheusremotewrite ]

  extensions: [ health_check ]